# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CS598MP3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DataFrameMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataFrameMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataFrameMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataFrameMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataFrameMetadata
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DataFrameMetadata
    def NumRows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # DataFrameMetadata
    def NumColumns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def DataFrameMetadataStart(builder):
    builder.StartObject(3)

def Start(builder):
    DataFrameMetadataStart(builder)

def DataFrameMetadataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    DataFrameMetadataAddName(builder, name)

def DataFrameMetadataAddNumRows(builder, numRows):
    builder.PrependInt64Slot(1, numRows, 0)

def AddNumRows(builder, numRows):
    DataFrameMetadataAddNumRows(builder, numRows)

def DataFrameMetadataAddNumColumns(builder, numColumns):
    builder.PrependInt64Slot(2, numColumns, 0)

def AddNumColumns(builder, numColumns):
    DataFrameMetadataAddNumColumns(builder, numColumns)

def DataFrameMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return DataFrameMetadataEnd(builder)
