# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CS598MP3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloatColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloatColumn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFloatColumn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FloatColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloatColumn
    def FloatValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # FloatColumn
    def FloatValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # FloatColumn
    def FloatValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloatColumn
    def FloatValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FloatColumnStart(builder):
    builder.StartObject(1)

def Start(builder):
    FloatColumnStart(builder)

def FloatColumnAddFloatValues(builder, floatValues):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(floatValues), 0)

def AddFloatValues(builder, floatValues):
    FloatColumnAddFloatValues(builder, floatValues)

def FloatColumnStartFloatValuesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartFloatValuesVector(builder, numElems):
    return FloatColumnStartFloatValuesVector(builder, numElems)

def FloatColumnEnd(builder):
    return builder.EndObject()

def End(builder):
    return FloatColumnEnd(builder)
