# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CS598MP3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntColumn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntColumn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntColumn
    def IntValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # IntColumn
    def IntValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # IntColumn
    def IntValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IntColumn
    def IntValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def IntColumnStart(builder):
    builder.StartObject(1)

def Start(builder):
    IntColumnStart(builder)

def IntColumnAddIntValues(builder, intValues):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(intValues), 0)

def AddIntValues(builder, intValues):
    IntColumnAddIntValues(builder, intValues)

def IntColumnStartIntValuesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartIntValuesVector(builder, numElems):
    return IntColumnStartIntValuesVector(builder, numElems)

def IntColumnEnd(builder):
    return builder.EndObject()

def End(builder):
    return IntColumnEnd(builder)
