# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CS598MP3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StringColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StringColumn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStringColumn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StringColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StringColumn
    def StringValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # StringColumn
    def StringValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StringColumn
    def StringValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StringColumnStart(builder):
    builder.StartObject(1)

def Start(builder):
    StringColumnStart(builder)

def StringColumnAddStringValues(builder, stringValues):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stringValues), 0)

def AddStringValues(builder, stringValues):
    StringColumnAddStringValues(builder, stringValues)

def StringColumnStartStringValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStringValuesVector(builder, numElems):
    return StringColumnStartStringValuesVector(builder, numElems)

def StringColumnEnd(builder):
    return builder.EndObject()

def End(builder):
    return StringColumnEnd(builder)
